controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_lucky_number:
    path: /test/lucky
    controller: App\Controller\LuckyController::number

app_welcome:
    path: /welcome
    controller: App\Controller\Welcome

app_contact:
    path: /test/contact
    controller: App\Controller\ContactController::contact